# This service handles the setting up of the modes of operation for a CiA402 drives on multiple DoFs.

# Modes of Operation
uint8 MODE_NO_MODE=0
uint8 MODE_PROFILED_POSITION=1
uint8 MODE_PROFILED_VELOCITY=3
uint8 MODE_PROFILED_TORQUE=4
uint8 MODE_HOMING=6
uint8 MODE_INTERPOLATED_POSITION=7
uint8 MODE_CYCLIC_SYNC_POSITION=8
uint8 MODE_CYCLIC_SYNC_VELOCITY=9
uint8 MODE_CYCLIC_SYNC_TORQUE=10

int32[] modes_of_operation
---
bool success
